# environments/staging/my-app/kustomization.yaml

namespace: staging
replicas:
  - name: todos-deployment
    count: 1
images:
  - name: emmamichael/todos-test
    newTag: v0.1.0
resources:
  - ../../../base