# environments/staging/my-app/kustomization.yaml

namespace: production
replicas:
  - name: todos-deployment
    count: 1
images:
  - name: emmamichael/todos-test
    newTag: v0.1.0.2
bases:
  - ../../../base

patches:
  - target:
      kind: Service
      name: todos-service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 4000

  - target:
      kind: PersistentVolume
      name: postgres-pv-test
    patch: pv-patch.yaml  

# resources:
#   - ../../base/service.yaml
#   - ../../base/secret.yaml
#   - ../../base/postgres-deployment.yaml
#   - ../../base/persistent-volume.yaml
#   - ../../base/persistent-volume-claim.yaml
#   - ../../base/namespace.yaml
#   - ../../base/deployment.yaml

  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc-test
    patch: pvc-patch.yaml          