apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
  labels:
    app: todos
spec:
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: todos
          imagePullPolicy: Always
          image: emmamichael/todos-test
          ports:
            - containerPort: 80